application:
    receiver: antoine.haz@gmail.com
spring:
    application.name: alerts
    mail:
        host: smtp.gmail.com
        port: 587
        username: antoine.haz@gmail.com
        password: zsjx msme nrzr msep
        properties:
            mail: 
                smtp:
                    auth: true
                    starttls:
                        enable: true
