name: maven-release
on: 
    workflow_dispatch:

jobs:
    maven-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # - uses: s4u/setup-maven-action@v1.18.0
            #   with:
            #     java-version: 21
            - uses: qcastel/github-actions-maven-release@master
              with:
                release-branch-name: "master"
          
                git-release-bot-name: "release-bot"
                git-release-bot-email: "release-bot@example.com"
          
                access-token: ${{ secrets.GITHUB_TOKEN }}