name: maven-release
on: 
    workflow_dispatch:

jobs:
    maven-release:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - uses: s4u/setup-maven-action@v1.18.0
              with:
                java-version: 21
            - run: mvn --batch-mode release:prepare