name: maven-release
on: 
    workflow_dispatch:

jobs:
    maven-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: s4u/setup-maven-action@v1.18.0
              with:
                java-version: 21
            - run: |
                git config user.email "antoine.hazebrouck5@gmail.com"
                git config user.name "Antoine HAZEBROUCK"
                mvn --batch-mode release:prepare